### ISSUE TITLE
Allow the user to specify the fee_payer name

### ISSUE THREAD

**Issue by julianzamt** [Codigo-io/platform#32]
**Is your enhancement request related to a problem? Please describe.**
Sometimes a user wants to give the first signer of a transaction a meaningful name.
However, in the generated code, if the rent payer of an initialization is not specified, it end up appearing as fee_payer, thus being not buildeable.

CIDL:
```
- name: create_global_state
    solana:
      signers:
        - name: admin
    inputs:
      - name: bps
        type: u16
      - name: global_state
        type: GlobalState
        solana:
          attributes: [ init ]
```

Generated lib code:
```
#[account(mut, signer)]
      pub admin : AccountInfo<'info>,
      #[account(init, space=42, payer=fee_payer, seeds = [b"global"], bump)] ---> Notice the `fee_payer`
      pub global_state: Account<'info,GlobalState>,
```

**Describe the solution you'd like**
If not specified different, to assume the first signer of the list is the rent payer of accounts creation.
If not specified any signer, default to the `fee_payer` name, but only in that case.
Allow the user to use their own var names.
